### ISSUE TITLE
Icon is wrong size

### ISSUE THREAD

**Issue by amiantos** [amiantos/dotbeat#1]
The icon is a bit off, the red border area should be empty. Pretty easy to see how the dotBeat icon is too large compared to other icons.

![image](https://user-images.githubusercontent.com/1126616/145652721-45b35e02-91a2-4321-b07a-3cf8d3a1bf42.png)

**Comment by Bustycat** [comment]
Because it does not follow the template.
https://developer.apple.com/design/resources/#macos-apps

**Comment by amiantos** [comment]
Fixed in commit https://github.com/amiantos/dotbeat/commit/2e0fbb63c75f5d9b08a2b7eca83afc6bd47580dd
