### ISSUE TITLE
Converting time zones needs improvement

### ISSUE THREAD

**Issue by Melonking906** [amiantos/dotbeat#2]
Overall the timezone converter is quite frustrating to use. For example, if I want to get the beat time for 5pm, it's very hard to get the slider to exactly 17:00.

This could be vastly improved if the slider snapped to multiples of 5 and/or allowed you to type in the numerical time you'd like to convert to.

It would also be helpful to have a searchable drop down of global cities so that I can select a city to see exactly what time it will be in that city without having to know what timezone it's in to start with.

**Comment by amiantos** [comment]
> Overall the timezone converter is quite frustrating to use. For example, if I want to get the beat time for 5pm, it's very hard to get the slider to exactly 17:00.

I think part of the difficulty of this is that .beat doesn't correspond exactly to every minute of every day. Some people have implemented decimal points in .beat to account for this but I decided to not allow for decimal .beat. So the bar is configured to go by .beat measures, not minutes, so it can be near impossible to land on some certain values.

> This could be vastly improved if the slider snapped to multiples of 5 and/or allowed you to type in the numerical time you'd like to convert to.

Good suggestion.

> It would also be helpful to have a searchable drop down of global cities so that I can select a city to see exactly what time it will be in that city without having to know what timezone it's in to start with.

Also a good suggestion.

These are relatively minor additions, I'll take a peek and see how quickly I can make these changes.

**Comment by amiantos** [comment]
Status update on this (finally getting around to it, sorry for the lag).

https://github.com/amiantos/dotbeat/assets/1126616/90d69162-b875-4a13-8959-4b0416145ed8

The macOS UX for this seems a little funky, gonna explore ways to make it a little less flaky before I release it.

**Comment by amiantos** [comment]
Here we go, this functionality is more like the ideal I think.

https://github.com/amiantos/dotbeat/assets/1126616/1148add7-28bb-4274-9378-eb676aab1ad1

**Comment by amiantos** [comment]
@Melonking906 wanna try this out and let me know what you think? https://amiantos.s3.amazonaws.com/dotBeat-v1.1.zip

**Comment by Melonking906** [comment]
Ah thanks! This seems to work well. I would say the timezone search could be improved by connecting it to a database of cities. For example if I want to arrange a meeting with someone in Las Vegas, I don't necessarily know what timezone Las Vegas is in, so it would be helpful if I could just type the city name and have it resolve to the correct timezone.

Relating to the grid below the search:

I would also say the grid of timezones below could be turned into timezone links - e.g. clicking the tokyo time will switch your timezone selection to tokyo.

Finally, I would put the local timezone text in bold on the grid, so you can easily references your local time when doing conversions. This would also be helpful as a quick way to reset the timezone selection to your local time when used in conjunction with the links idea.

**Comment by amiantos** [comment]
@Melonking906 Implemented all your requests... You can now search by a database of city names, your local timezone is highlighted with a box outline, and you can click on any of the texts in the grid to set the top to that timezone.

https://github.com/amiantos/dotbeat/assets/1126616/5839bcc5-6df6-4314-91e6-60b0caa20852

Updated version at the same link: https://amiantos.s3.amazonaws.com/dotBeat-v1.1.zip

**Comment by Melonking906** [comment]
That's looking really good! The timezone highlight does not seem to be working for me (I'm in Ireland so GMT+1 should be highlighted) but its not; otherwise all seems to be great! - I'm guessing your in LA and its only highlighting a direct city match?

EDIT:
Is there a particular need for the duplicate timezones like Brisbane and Sydney?

**Comment by amiantos** [comment]
> That's looking really good! The timezone highlight does not seem to be working for me (I'm in Ireland so GMT+1 should be highlighted) but its not; otherwise all seems to be great! - I'm guessing your in LA and its only highlighting a direct city match?

Hmm, I'll fiddle with this and see if I can fix it.

> EDIT: Is there a particular need for the duplicate timezones like Brisbane and Sydney?

This may not be accurate now but when I was building the grid, Brisbane and Sydney actually have unique timezones during the summer where there is an hour difference between them, but it's not relevant any other time of the year. Weird!

**Comment by amiantos** [comment]
@Melonking906 I changed the highlight to highlight based on matching GMT offset, which means you can end up with multiple times highlighted at once, which might be weird, but it seems like the best solution. Before it was trying to exact match your current timezone to one of the grid ones, which may not work since your exact timezone may not be one of the items in the grid.

![image](https://github.com/amiantos/dotbeat/assets/1126616/793755c4-b61a-4679-8ecc-8bf1d928be13)

New version: https://amiantos.s3.amazonaws.com/dotBeat-v1.1.zip

**Comment by Melonking906** [comment]
It looks ok, its pretty clear that these are the places that match my time:
![Screenshot 2024-06-07 at 20 05 43](https://github.com/amiantos/dotbeat/assets/1700367/fb82a0b2-a9e1-47da-b604-801d947d8b98)

A simple suggested fix for the duplicates; put a check on each grid entry that hides the entry if the previous grid entry has the same timezone - that way duplicates would disappear when timezone are in sync, but re-appear when say Brisbane switches to daylight savings time and Sydney does not. That said, I don't think its a huge issue.

**Comment by amiantos** [comment]
> A simple suggested fix for the duplicates; put a check on each grid entry that hides the entry if the previous grid entry has the same timezone - that way duplicates would disappear when timezone are in sync, but re-appear when say Brisbane switches to daylight savings time and Sydney does not. That said, I don't think its a huge issue.

Yeah I think this is rife with peril... like if you're in Lagos and it only highlights London, that feels like a bug. Or if you're not in London or Lagos and it highlights one but not the other, that could feel like a bug.

I think if I wanted to go deep on this the best solution would be to grab your local timezone, and then replace one of the matching GMT offsets in the grid with your actual local timezone, then I could highlight it precisely as your exact timezone. I should also revert the grid back to showing the timezone name and not the city name, to better avoid the mismatch between what appears in the box and what is shown in the grid, I forgot that I changed that and it makes the Brisbane/Sydney difference less clear.

Well, I've talked about it enough that I want to do it now...

**Comment by amiantos** [comment]
@Melonking906 okay, here we go

Changes:
1. The custom time box defaults to Biel, Switzerland, the home time of Swatch Internet Time
2. The grid labels are the "Standard Time" timezone names again like it was originally
3. Your timezone is now automatically inserted into the right place in the grid and highlighted

Same url: https://amiantos.s3.amazonaws.com/dotBeat-v1.1.zip

**Comment by amiantos** [comment]
- Switched Biel Switzerland initial display to accurate "Biel Mean Time", the actual home time of Swatch Internet Time, which is actually CET in winter and WEST in summer, annoying...

I think this is it for 1.1...

Same url: https://amiantos.s3.amazonaws.com/dotBeat-v1.1.zip

**Comment by amiantos** [comment]
Oh, and if you like dotBeat more now, please consider buying it on the Mac App Store and leaving a positive review. Thank you!

https://apps.apple.com/us/app/dotbeat-internet-time/id1599168929?mt=12

I just submitted 1.1 to App Review so it's not up on the store just yet.

**Comment by Melonking906** [comment]
Thanks for the work, and I would, but I already did last year (I gave it 5 stars)!

**Comment by amiantos** [comment]
> Thanks for the work, and I would, but I already did last year (I gave it 5 stars)!

Thank you 🙏🏻  Let me know if anything else bugs you.
